<a href="https://colab.research.google.com/github/KudasaiCode/Arrays-with-NumPy-and-Pandas/blob/master/NumPy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Arrays for 1D Data



---



---



## Initializing and Converting to Numpy Array

In [0]:
import numpy as np

### Create array of zeros

In [0]:
array1 = np.zeros(3)
print(array1)

[0. 0. 0.]


In [0]:
array2 = np.zeros(5)
print(array2)

[0. 0. 0. 0. 0.]




---



### Create array of ones

In [0]:
array1 = np.ones(5)
print(array1)

[1. 1. 1. 1. 1.]




---



### Create a NumPy Array

In [0]:
array2 = np.array([1, 2, 3, 4, 5])
print(array2)

[1 2 3 4 5]




---



###Convert Python list into array

In [0]:
python_list = [1,2,3,4,5,6,7,8]

numpy_array = np.array(python_list)
print(python_list, numpy_array)

[1, 2, 3, 4, 5, 6, 7, 8] [1 2 3 4 5 6 7 8]




---



### Arrange

In [0]:
array1 = np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [0]:
array2 = np.arange(2, 8)
print(array2)

[2 3 4 5 6 7]


In [0]:
# Last value makes it so that it only includes every other number
array3 = np.arange(2, 12, 4)
print(array3)

[ 2  6 10]


In [0]:
array4 = np.arange(5,51, 5)
print(array4)

[ 5 10 15 20 25 30 35 40 45 50]


In [0]:
array5 = np.arange(100, 1001, 10)
print(array5)

[ 100  110  120  130  140  150  160  170  180  190  200  210  220  230
  240  250  260  270  280  290  300  310  320  330  340  350  360  370
  380  390  400  410  420  430  440  450  460  470  480  490  500  510
  520  530  540  550  560  570  580  590  600  610  620  630  640  650
  660  670  680  690  700  710  720  730  740  750  760  770  780  790
  800  810  820  830  840  850  860  870  880  890  900  910  920  930
  940  950  960  970  980  990 1000]




---



### Linspace

In [0]:
# USE linspace when we want a fixed length we'd like to use
array6 = np.linspace(0, 101, 10)
print(array6)

[  0.          11.22222222  22.44444444  33.66666667  44.88888889
  56.11111111  67.33333333  78.55555556  89.77777778 101.        ]


In [0]:
array7 =  np.linspace(1,20,3)
print(array7)

[ 1.  10.5 20. ]




---



## Accessing and Modifying Numpy Arrays

### Accessing through Indexing

In [0]:
#Works the same way as python list

print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [0]:
print(array1[0])
print(array1[9])

print(array2)
print(array2[3])

print(array1)

0
9
[2 3 4 5 6 7]
5
[0 1 2 3 4 5 6 7 8 9]


In [0]:
new_array = [x for x in array1 if x%2 == 0]
print(new_array)

new_array2 = [new_array[x] * 13    for x in range(5) if new_array[x] <= new_array[-1]]
print(new_array2)

[0, 2, 4, 6, 8]
[0, 26, 52, 78, 104]




---



#### Using np.nditer()

$np.nditer()$

iterates over array

In [0]:
print(new_array2)
actual_array = np.array(new_array2)
print(actual_array)

actual_list_of_array = list()

for i in np.nditer(actual_array):
  print(i)
  actual_list_of_array.append(i)
  print("Appended ", i, " to List")
  

[0, 26, 52, 78, 104]
[  0  26  52  78 104]
0
Appended  0  to List
26
Appended  26  to List
52
Appended  52  to List
78
Appended  78  to List
104
Appended  104  to List




---



### Selection through Slicing

In [0]:
print(actual_array)
print(actual_array[1:4])
print(actual_array[2:3])
print(actual_array[2:4])

[  0  26  52  78 104]
[26 52 78]
[52]
[52 78]


In [0]:
array = np.arange(26)
print(array)

print(array[5:-2])
print(array[:-15])
print(array[:11])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]




---



### Append/Concatenation

In [0]:
np.append(array, 10000 + actual_array[2])

array([    0,     1,     2,     3,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25, 10052])

In [0]:
arrayX = np.arange(21)
arrayY = np.arange(20, 41)
print('arrayX = ', arrayX, '\narrayY = ', arrayY, '\n')

arrayXY = np.append(arrayX, arrayY[1:])
print('concatenated: ', arrayXY)

arrayX =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] 
arrayY =  [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40] 

concatenated:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


In [0]:
arrayXY = np.append(arrayXY, [80, 120, 160, 170])
print(arrayXY)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  80 120 160  80 120 160  80 120 160 170]




---



### Split

In [0]:
np.split(arrayXY, 3)

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]),
 array([ 34,  35,  36,  37,  38,  39,  40,  80, 120, 160,  80, 120, 160,
         80, 120, 160, 170])]

In [0]:
np.split(arrayXY, [7, 12, 13, 19])

[array([0, 1, 2, 3, 4, 5, 6]),
 array([ 7,  8,  9, 10, 11]),
 array([12]),
 array([13, 14, 15, 16, 17, 18]),
 array([ 19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,
         32,  33,  34,  35,  36,  37,  38,  39,  40,  80, 120, 160,  80,
        120, 160,  80, 120, 160, 170])]



---



### Get Info

In [0]:
# Size
arrayXY.size

51

In [0]:
# Shape for checking the amount of dimensions
arrayXY.shape

(51,)



---



## Numpy Array Math Operations

###Scalar and Vector Addition

$np.add()$

In [0]:
print(arrayXY)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  80 120 160  80 120 160  80 120 160 170]


In [0]:
print(arrayXY + 5)

[  5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22
  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40
  41  42  43  44  45  85 125 165  85 125 165  85 125 165 175]


In [0]:
x1 = np.array([1, 2, 3])
x2 = np.array([10, 20, 30])
print(x1, x2)

np.add(x1, x2)


# np.add(x1, arrayXY) Shapes are different. Cannot add components that don't exist. 

[1 2 3] [10 20 30]


array([11, 22, 33])



---



### Scalar and Vector Subtraction

$np.subtract()$

In [0]:
print(arrayXY - 100)

[-100  -99  -98  -97  -96  -95  -94  -93  -92  -91  -90  -89  -88  -87
  -86  -85  -84  -83  -82  -81  -80  -79  -78  -77  -76  -75  -74  -73
  -72  -71  -70  -69  -68  -67  -66  -65  -64  -63  -62  -61  -60  -20
   20   60  -20   20   60  -20   20   60   70]


In [0]:
print(np.subtract(x1, x2))

print(np.subtract(x2,x1))

[ -9 -18 -27]
[ 9 18 27]


In [0]:
x2 - x1

array([ 9, 18, 27])



---



### Scalar and Vector Multiplication

$np.multiply()$

In [0]:
print(x1)
print(x1*4)

[1 2 3]
[ 4  8 12]


In [0]:
print(x1, x2)

np.multiply(x1, x2/5)

[1 2 3] [10 20 30]


array([ 2.,  8., 18.])



---



#### DOT Multiplication

$np.dot()$

In [0]:
print(np.dot(x1, x2)) #Mutiplies by component, then adds
# 10 + 30 + 50

140




---



### Scalar and Vector Division

$np.divide()$

In [0]:
print(x1, x2)
np.divide(x1,x2/10)

[1 2 3] [10 20 30]


array([1., 1., 1.])



---



### Exponential/Roots

$np.power()$

In [0]:
print(np.power(x1,2))
np.power(x2,2)

[1 4 9]


array([100, 400, 900])

In [0]:
print(x1, x2)
print(x1**2, x2**2)

[1 2 3] [10 20 30]
[1 4 9] [100 400 900]


In [0]:
roots_list = [x*x for x in range(12)]
print(roots_list)

roots_array = np.array(roots_list)
print('\n', roots_array)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121]

 [  0   1   4   9  16  25  36  49  64  81 100 121]


In [0]:
rooted_array = np.power(roots_array, 0.5)
print('square root of: ', roots_array)
print(' = ', rooted_array)

square root of:  [  0   1   4   9  16  25  36  49  64  81 100 121]
 =  [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]




---



## NumPy Array Statistics Operations

###Min/Max/Range

$.min()$  and $.max()$

In [0]:
print('x1: ', x1, '\nx2 ', x2)

x1:  [1 2 3] 
x2  [10 20 30]


In [0]:
x1_min = x1.min()
print(x1_min)

1


In [0]:
print(x1.max())
x1_max = x1.max()
print(x1_max)

3
3


In [0]:
# For the range, subtract the max() and min() values

x1_range = x1_max - x1_min
print(x1_range)

2


In [0]:
print(x2.max() - x2.min())
x2_range = x2.max() - x2.min() # 30 - 10

20




---



###Sum/Total

$.sum()$

adds all the values in the array

In [0]:
x1.sum()

6

In [0]:
x2.sum()

60

In [0]:
arrayXY.sum()

2070



---



###Count/Frequency

$np.unique()$

In [0]:
# np.unique returns an array with only th eunique elements. No repeats

In [0]:
np.unique([2, 2, 3, 1, 3, 4, 1, 10, 19, 10, 29, 1, 2, 3, 4, 4, 5, 1, 6, 8])

array([ 1,  2,  3,  4,  5,  6,  8, 10, 19, 29])



---



###Mean/Median

$Mean = {1 \over n} \sum\limits_{i = 1}^{n} {Observation_i} = {Observation_{1}} + {Observation_{2}}... {Observation_{n}}$

$np.mean()$ and $np.median()$

In [0]:
print(np.mean(arrayXY))

mean = np.divide(np.sum(arrayXY), arrayXY.size)
print(mean)           

40.588235294117645
40.588235294117645


In [0]:
print(arrayXY)
arrayXY.size

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  80 120 160  80 120 160  80 120 160 170]


51

In [0]:
print(np.median(arrayXY))


25.0


In [0]:
np.median(x1)

2.0

In [0]:
np.median([1, 2, 3, 4, 5, 6])

3.5

####  Mode

In [0]:
# Returns the array with unique elements only and another array with how many times
# the element appears in the list. 

# Used to find MODE
np.unique([2, 2, 3, 1, 3, 4, 1, 10, 19, 10, 29, 1, 2, 3, 4, 4, 5, 1, 6, 8], return_counts=True)

# 1 is found 4 time, 2, 3 and 4 are found 3 times. 
# 10 is found 2 times

# the MODE is 1 since it appears the most times

(array([ 1,  2,  3,  4,  5,  6,  8, 10, 19, 29]),
 array([4, 3, 3, 3, 1, 1, 1, 2, 1, 1]))



---



### Variance/Standard Deviation

$variance = {{((x_i - mean)^2 + {(x_{i+1} - mean)^2}......)}\over Amount\_of\_Observations }$

$np.var()$

returns the variance

In [0]:
print(np.var(arrayXY)) #the pretty way

# The Ugly way
adding = 0
for x in np.nditer(arrayXY):
  adding = np.power(x - np.mean(arrayXY), 2) + adding
print(adding/arrayXY.size)

2082.791234140715
2082.791234140715




---



$np.std()$

returns the standard deviation

In [0]:
print(np.std(arrayXY))

# Finding the standard deviation square-rooting the variance.
# aka, the ugly way
standard_deviation = np.power(np.var(arrayXY), .5)
print(standard_deviation)

45.63760767328536
45.63760767328536




---



### Correlation coefficient

$Correlation = {{1\over n} \sum\limits_{i=1}^{n} {(stnd\_unit\_height_i  -  mean\_height) \over stnd\_dev\_height} \times {(stnd\_unit\_weight_i - mean\_weight) \over stnd\_dev\_weight}}$

In [0]:
height = np.array([72, 75, 63, 81, 62])
weight = np.array([125, 140, 140, 189, 130])

mean_height = np.mean(height)
mean_weight = np.mean(weight)

stnd_dev_height = np.std(height)
stnd_dev_weight = np.std(weight)

stnd_unit_height = np.array([(x - mean_height)/stnd_dev_height for x in height])
stnd_unit_weight = np.array([(x - mean_weight)/stnd_dev_weight for x in weight])

correlation_coeff = np.multiply(stnd_unit_height, stnd_unit_weight).sum() / stnd_unit_height.size
print('\nCorrelation Coefficient = ', correlation_coeff)


Correlation Coefficient =  0.6958125111028929


# Pandas Series for 1D Data



---



---



## Initializing and Converting to Panda Series

In [0]:
import pandas as pd
import numpy as np
from typing import List, Dict, Tuple



---



### Create Series without index (list)

$pd.Series()$

Series are a list / dictionary hybrid

In [0]:
s1 = pd.Series([1, 2, 3, 4, 5])
print(s1)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [0]:
numbers_list: List[int] = [10, 20, 30, 40, 50]
print(numbers_list)

s2 = pd.Series(numbers_list)
print(s2)

[10, 20, 30, 40, 50]
0    10
1    20
2    30
3    40
4    50
dtype: int64




---



### Create Series with Index (dictionary)

In [0]:
sd1 = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5})
print(sd1)
# They keys become the indices

a    1
b    2
c    3
d    4
e    5
dtype: int64




---



### Convert NumPy Array to Series

In [0]:
# Converting Python list into NumPy Array
array_numbers = np.array(numbers_list)
print(array_numbers)

[10 20 30 40 50]


In [0]:
# Converting NumPy Array to Pandas Series
series_numbers = pd.Series(array_numbers)
print(series_numbers)

0    10
1    20
2    30
3    40
4    50
dtype: int64




---



#### Creating series for later use

In [0]:
# Python Lists
list1: List[float] = [1.5, 2.5, 3.5, 4.5, 5.5, 6.5]
list2: List[int] = [10, 15, 20, 25]
# Dictionary
dict1: Dict[str, int] = {'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4}
dict2: Dict[int, int] = {1:1, 2:2, 3:3, 4:4, 5:5, 6:6, 7:7}
  
# NumPy Arrays
array1 = np.arange(1, 51)
array2 = np.arange(100, 201, 2)
array3 = np.array(list1)
array4 = np.append(array1[24:], array2)

# Converting to Pandas Series
series1 = pd.Series(list1)
series2 = pd.Series(list2)
series3 = pd.Series(array1)
series4 = pd.Series(array2)
series5 = pd.Series(array3)
series6 = pd.Series(array4)
series7 = pd.Series(dict1)
series8 = pd.Series(dict2)

In [0]:
def print_all(series, array, list, dict):
  return print("series:\n{0}\n\narray:\n{1}\n\nlist:\n{2}\n\ndict:\n{3}".format(series, array, list, dict))

In [0]:
print_all(series1, array2, list1, dict2)

series:
0    1.5
1    2.5
2    3.5
3    4.5
4    5.5
5    6.5
dtype: float64

array:
[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158 160 162 164 166 168 170
 172 174 176 178 180 182 184 186 188 190 192 194 196 198 200]

list:
[1.5, 2.5, 3.5, 4.5, 5.5, 6.5]

dict:
{1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7}




---



## Accessing and Selection

In [0]:
# Providing column number
print(series2[1])
print(series2)

15
0    10
1    15
2    20
3    25
dtype: int64




---



### Selection by Label

$.loc()$

In [0]:
print(series7.loc['d']) # Row 'd' returns 3
print(series7.loc['a'])

print(series7)

3
0
a    0
b    1
c    2
d    3
e    4
dtype: int64




---



###Selection by Position

$.iloc()$

uses index parameter

In [0]:
print(series7.iloc[3]) # index-loc. the index is the row, returns column
print(series7.iloc[0])
print(series7.loc['a']) # Row 'a' has index of 0

3
0
0




---



### Selection by Slicing

In [0]:
series7[0:4] # Same as python list and NumPy Arrays

a    0
b    1
c    2
d    3
dtype: int64



---



### Iterations

In [0]:
for item in series7:
  print(series7.iloc[item]) 

0
1
2
3
4




---



### Access by Condition (AND OR NOT)

$AND$

In [0]:
print(series4[(series4 >= 130) & (series4 < 160)])

15    130
16    132
17    134
18    136
19    138
20    140
21    142
22    144
23    146
24    148
25    150
26    152
27    154
28    156
29    158
dtype: int64




---



$OR$

In [0]:
print(series4[(series4 <= 120) | (series4 >= 190)])

0     100
1     102
2     104
3     106
4     108
5     110
6     112
7     114
8     116
9     118
10    120
45    190
46    192
47    194
48    196
49    198
50    200
dtype: int64




---



$NOT$

In [0]:
print(series4[~(series4 > 121)]) # returns all values less than 121

0     100
1     102
2     104
3     106
4     108
5     110
6     112
7     114
8     116
9     118
10    120
dtype: int64


In [0]:
print(series4[series4 <= 140])

0     100
1     102
2     104
3     106
4     108
5     110
6     112
7     114
8     116
9     118
10    120
11    122
12    124
13    126
14    128
15    130
16    132
17    134
18    136
19    138
20    140
dtype: int64


In [0]:
print(series4[series4 == 100])
print(series4[series4 == 130])


0    100
dtype: int64
15    130
dtype: int64




---



#### Limits/Sorting

$.head()$

returns values in the beginning

In [0]:
print(series4.head()) # Default of head() returns first 5 values

0    100
1    102
2    104
3    106
4    108
dtype: int64


In [0]:
print(series5.head(3))

0    1.5
1    2.5
2    3.5
dtype: float64




---



$.tail()$

returns values at the end

In [0]:
print(series6.tail())

72    192
73    194
74    196
75    198
76    200
dtype: int64


In [0]:
print(series6.tail(2))

75    198
76    200
dtype: int64


---

$.sort\_values()$

not permanent. Only returns different view

In [0]:
series9 = pd.Series([2, 4, 5, 1, 4, 1, 8, 9, 3, 6, 3,4 , 8, 4, 4, 4, 4, 4, 4, 3, 2])

In [0]:
series9.sort_values()

5     1
3     1
0     2
20    2
10    3
8     3
19    3
18    4
17    4
16    4
15    4
14    4
13    4
4     4
11    4
1     4
2     5
9     6
6     8
12    8
7     9
dtype: int64

In [0]:
series9.sort_values().unique()

array([1, 2, 3, 4, 5, 6, 8, 9])

In [0]:
np.unique(series9, return_counts=True)

(array([1, 2, 3, 4, 5, 6, 8, 9]), array([2, 2, 3, 9, 1, 1, 2, 1]))

---

## Modifying Panda Series

###Append

$array\_1.append(array\_2)$

In [0]:
print(series1.append(series2))

0     1.5
1     2.5
2     3.5
3     4.5
4     5.5
5     6.5
0    10.0
1    15.0
2    20.0
3    25.0
dtype: float64


In [0]:
print(series2)

0    10
1    15
2    20
3    25
dtype: int64




---



$pd.concat([series1, series2])$

In [0]:
print(pd.concat([series1, series2]))

0     1.5
1     2.5
2     3.5
3     4.5
4     5.5
5     6.5
0    10.0
1    15.0
2    20.0
3    25.0
dtype: float64




---



###Deleting from Series

$.drop([ ])$

In [0]:
print(series2)

0    10
1    15
2    20
3    25
dtype: int64


In [0]:
print(series2.drop([1]))

0    10
2    20
3    25
dtype: int64


In [0]:
print(series2.drop(1))

0    10
2    20
3    25
dtype: int64




---



###Updating to Series

$series1.update(series2)$

matches indexes and updates on tha location

**Careful when changes are explicit**

In [0]:
s1 = pd.Series([12, 11, 10, 7, 6])
s2 = pd.Series([9, 8, 7, 6, 5, 4, 3], [3, 4, 5, 6, 7, 8, 9])

In [0]:
s1.update(s2)
print(s1)

0    12
1    11
2    10
3     9
4     8
dtype: int64


Values 7, 6, 5, 4, and 4 where not updated because $series1$ did not have any **index > 4**



---



## Panda Series Math Operations

similair to how NumPy does it

### Scalar and Vector Addition

In [0]:
series_added = series1 + series2
print(series_added)

0    11.5
1    17.5
2    23.5
3    29.5
4     NaN
5     NaN
dtype: float64


**Unlike Arrays, series may be added even whey they have different shapes**

In [0]:
array_added = array1 + array2
print(array_added)

ValueError: ignored



---



### Scalar and Vector Subtraction

In [0]:
print(series1 - series2)

0    -8.5
1   -12.5
2   -16.5
3   -20.5
4     NaN
5     NaN
dtype: float64




---



### Scalar and Vector Multiplication

In [0]:
series_mult = series1 * series2
print(series_mult)

0     15.0
1     37.5
2     70.0
3    112.5
4      NaN
5      NaN
dtype: float64




---



### Scalar and Vector Division

In [0]:
series_div = series4/series3
print(series_div.head(10))
print(series_div.tail())


0    100.000000
1     51.000000
2     34.666667
3     26.500000
4     21.600000
5     18.333333
6     16.000000
7     14.250000
8     12.888889
9     11.800000
dtype: float64
46    4.085106
47    4.041667
48    4.000000
49    3.960000
50         NaN
dtype: float64


In [0]:
print(series4.shape, series3.shape)

(51,) (50,)




---



### Exponentials/Roots

In [0]:
print(series8**(1/2))

1    1.000000
2    1.414214
3    1.732051
4    2.000000
5    2.236068
6    2.449490
7    2.645751
dtype: float64




---



## Panda Series Statistics Operations

Similair to NumPy statistic operations

###Min/Max/Range

In [0]:
s1_min = series7.min()
print(s1_min)

0


In [0]:
print(series7.max())

4


In [0]:
print(series7)

a    0
b    1
c    2
d    3
e    4
dtype: int64


In [0]:
s1_range = series1.max() - series1.min()
print(s1_range)

5.0




---



###Sum/Total

In [0]:
series2.sum()

70



---



###Count/Frequency

$series.value\_counts()$

In [0]:
print(series2)

0    10
1    15
2    20
3    25
dtype: int64


In [0]:
series2.value_counts()

15    1
20    1
10    1
25    1
dtype: int64

In [0]:
scount = pd.Series([1, 1, 1, 2, 2, 3, 3, 3, 3, 4, 4, 4, 8])

In [0]:
scount.value_counts()

3    4
4    3
1    3
2    2
8    1
dtype: int64



---



###Mean/Median

In [0]:
scount.mean()

3.0

In [0]:
scount.median()

3.0



---



###Variance/Standard Deviation

In [0]:
scount.var()

3.5

In [0]:
scount.std()

1.8708286933869707



---



###Quantile

$series.quantile()$

returns percentile

In [0]:
series = pd.Series([1, 25, 50, 75, 100])

In [0]:
series.quantile([.5])

0.5    50.0
dtype: float64

In [0]:
series = pd.concat([series, series2])
print(series)

0      1
1     25
2     50
3     75
4    100
0     10
1     15
2     20
3     25
dtype: int64


In [0]:
series.quantile([.9])

0.9    80.0
dtype: float64

In [0]:
series.quantile([.1, .2, .3, .4, .5])

0.1     8.2
0.2    13.0
0.3    17.0
0.4    21.0
0.5    25.0
dtype: float64



---



###Cumulative Sum

$series.cumsum()$

adds values cumulatively

In [0]:
series = pd.Series([1, 2, 3, 4, 5, 6])

In [0]:
series.cumsum()

0     1
1     3
2     6
3    10
4    15
5    21
dtype: int64



---



###Apply and Lambda

$series.apply()$

Allows pandas to apply an outside function to the values in the series

In [0]:
series.apply(np.sqrt)

0    1.000000
1    1.414214
2    1.732051
3    2.000000
4    2.236068
5    2.449490
dtype: float64

In [0]:
# Pandas alone does not have a square root function
series.sqrt()

AttributeError: ignored



---



In [0]:
s1

0    12
1    11
2    10
3     9
4     8
dtype: int64

In [0]:
s1.apply(lambda x: False if x <= 10 else True)

0     True
1     True
2    False
3    False
4    False
dtype: bool



---



# NumPy Matrices for 2D Data

In [0]:
import numpy as np

## Initializing and Converting to Numpy matrix

### Numpy Matrix by String

In [0]:
a = np.matrix('1 2 3; 4 5 6')
print(a)

[[1 2 3]
 [4 5 6]]


In [0]:
b = np.matrix('10 20 30 40; 20 40 60 80; 40 80 120 160')
print(b)

[[ 10  20  30  40]
 [ 20  40  60  80]
 [ 40  80 120 160]]




---



### Numpy Matrix by Double List

In [0]:
c = np.matrix([[1,2,3,4],[5,6,7,8]])
print(c)

[[1 2 3 4]
 [5 6 7 8]]




---



### Numpy Array to Matrix

In [0]:
a1 = np.array([1, 2, 3, 4, 5, 6, 7])
a2 = np.array([8, 9, 2, 3, 4, 5, 6])
m = np.matrix([a1, a2])
print(m)

[[1 2 3 4 5 6 7]
 [8 9 2 3 4 5 6]]


In [0]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5])
m2 = np.matrix([a1, a2])
print(m2) # Do not do

[[array([[1],
       [2],
       [3]]) array([[4],
       [5]])]]




---



##Accessing and Modifying Numpy Matrices

### Accessing Rows

**Rows pertain to the index number**

In [0]:
print(m[0])
print('\n', m[1])

[[1 2 3 4 5 6 7]]

 [[8 9 2 3 4 5 6]]




---



### Accessing Columns

**matrix [row : row, column]**

In [0]:
# Prints last column of all rows
print(m[ : , 6])

[[7]
 [6]]


In [0]:
# Prints fifth column of first row
print(m[0, 4])

5


In [0]:
many_rows = np.matrix('1 3 4 6 7 3; 1 2 3 4 1 2; 1 4 3 2 6 4')
print(many_rows)

[[1 3 4 6 7 3]
 [1 2 3 4 1 2]
 [1 4 3 2 6 4]]


In [0]:
print(many_rows[0:, 0:2]) # All rows, first 2 columns

[[1 3]
 [1 2]
 [1 4]]


In [0]:
print(many_rows[0:2, 4:6]) # first 2 rows, last 2 columns

[[7 3]
 [1 2]]


In [0]:
print(many_rows[0:3, 4:6]) # first 3 rows, 5th and 6th columns

[[7 3]
 [1 2]
 [6 4]]




---



### Accessing Elements

**matrix([row#, column#])**

In [0]:
print(m)

print(m[1, 6]) # second row, seventh column

[[1 2 3 4 5 6 7]
 [8 9 2 3 4 5 6]]
6


In [0]:
print(many_rows[2, 3]) # third row, fourth element

2




---



### Slicing the Matrix

** Same steps as above **

In [0]:
print(many_rows[:2, 1:3])

[[3 4]
 [2 3]]




---



### Iterating through the Matrix

$np.nditer(matrix)$ Is the recommended option

In [0]:
for i in np.nditer(many_rows):
  print(i) # It prints values by rows (list items)

1
3
4
6
7
3
1
2
3
4
1
2
1
4
3
2
6
4


In [0]:
print(many_rows)

[[1 3 4 6 7 3]
 [1 2 3 4 1 2]
 [1 4 3 2 6 4]]




---



### Get Info

$matrix.shape$ returns (row, column)

$matrix.size$ returns amount of elements

In [0]:
print(many_rows.shape)

(3, 6)


* Note: The size of the matrix is the **product** of my rows and columns

In [0]:
print(many_rows.size)

18




---



## Modifying the Matrix

### Inserting Rows

In [0]:
mat = np.matrix('10 15 20 25; 50 45 40 35')
print(mat)

[[10 15 20 25]
 [50 45 40 35]]


$np.vstack(matrix)$

Vertical-Stack: Adds more rows, hence why it grows vertically

In [0]:
mat = np.vstack((mat, [70, 65, 60, 55]))
print(mat)

[[10 15 20 25]
 [50 45 40 35]
 [70 65 60 55]]


In [0]:
mat = np.vstack((mat, [90, 85, 80, 75]))

In [0]:
print(mat)

[[10 15 20 25]
 [50 45 40 35]
 [70 65 60 55]
 [90 85 80 75]]


### Inserting Columns

$np.hstack(matrix)$

Horizontal-stack: appends columns

In [0]:
mat = np.hstack((mat, [[45],[55],[45],[35]]))
print(mat)

[[10 15 20 25 45]
 [50 45 40 35 55]
 [70 65 60 55 45]
 [90 85 80 75 35]]


### Modifying Rows/Columns



---



In [0]:
# Changing first row
mat[0] = [1, 2, 3, 4, 5]
print(mat)

[[ 1  2  3  4  5]
 [50 45 40 35 55]
 [70 65 60 55 45]
 [90 85 80 75 35]]


In [0]:
# Changin the second column
mat[:, 1] = [[-1], [-2], [-4],[-7]]
print(mat)

[[ 1 -1  3  4  5]
 [50 -2 40 35 55]
 [70 -4 60 55 45]
 [90 -7 80 75 35]]




---



### Deleting Rows/Columns

$ np.delete( matrix, row/column, axis)$

* axis = 0 works with rows
* axis = 1 works with columns

In [0]:
del_matrix = np.delete(mat, 2, 0) # Deleting the third row
print(del_matrix)

[[ 1 -1  3  4  5]
 [50 -2 40 35 55]
 [90 -7 80 75 35]]


In [0]:
print(mat.shape)
print(del_matrix.shape)

(4, 5)
(3, 5)


In [0]:
del_matrix = np.delete(del_matrix, -1, 1) # Deleting last column
print(del_matrix)

[[ 1 -1  3  4]
 [50 -2 40 35]
 [90 -7 80 75]]


In [0]:
del_matrix = np.delete(del_matrix, 1, 1) # Deleting the second column
print(del_matrix)

[[ 1  3  4]
 [50 40 35]
 [90 80 75]]


In [0]:
del_matrix.shape

(3, 3)



---



### Reshape

$matrix.reshape( row, column )$

In [0]:
matrix = np.matrix('1 2 3; 4 5 6; 7 8 9; 10 11 12; 13 14 15; 16 17 18')
print(matrix, matrix.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]] (6, 3)


* Shape must be consistent. (6, 3) = 18 

* So the reshape $row\times column$ must also equal $18$

In [0]:
matrix.reshape(9, 2)

matrix([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16],
        [17, 18]])

In [0]:
print(matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [0]:
matrix.reshape(1, 18)

matrix([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18]])



---



### Transpose Matrix

$matrix.T$

In [0]:
print(matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [0]:
transposed = matrix.T

In [0]:
print(transposed)

[[ 1  4  7 10 13 16]
 [ 2  5  8 11 14 17]
 [ 3  6  9 12 15 18]]


In [0]:
transposed.T

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])



---



## Numpy Matrix Math Operations

* Same as with arrays

### Scalar and Vector Addition

In [0]:
print(matrix+20)

[[21 22 23]
 [24 25 26]
 [27 28 29]
 [30 31 32]
 [33 34 35]
 [36 37 38]]


In [0]:
print(np.add(transposed, 3))

[[ 4  7 10 13 16 19]
 [ 5  8 11 14 17 20]
 [ 6  9 12 15 18 21]]




---



* Rows and columns must match for the addition to occure

In [0]:
print(np.add(transposed, matrix))

ValueError: ignored

In [0]:
transposed2 = matrix.reshape(3, 6)

In [0]:
print(transposed, '\n\n', transposed2)

[[ 1  4  7 10 13 16]
 [ 2  5  8 11 14 17]
 [ 3  6  9 12 15 18]] 

 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [0]:
print(np.add(transposed, transposed2))

[[ 2  6 10 14 18 22]
 [ 9 13 17 21 25 29]
 [16 20 24 28 32 36]]


In [0]:
transposed2 = np.hstack((transposed2, [[7],[7],[7]]))
print(transposed2)

[[ 1  2  3  4  5  6  7]
 [ 7  8  9 10 11 12  7]
 [13 14 15 16 17 18  7]]


In [0]:
print(np.add(transposed, transposed2))

ValueError: ignored



---



### Scalar and Vector Subtraction

In [0]:
print(transposed, '\n\n', transposed2)

[[ 1  4  7 10 13 16]
 [ 2  5  8 11 14 17]
 [ 3  6  9 12 15 18]] 

 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [0]:
print(transposed - 1)

[[ 0  3  6  9 12 15]
 [ 1  4  7 10 13 16]
 [ 2  5  8 11 14 17]]


In [0]:
print(np.subtract(transposed2, transposed))

[[  0  -2  -4  -6  -8 -10]
 [  5   3   1  -1  -3  -5]
 [ 10   8   6   4   2   0]]




---



### Scalar and Vector Multiplication

* **Matrix Multiplication requires that matrixA columns = matrixB Row**

* np.dot(A, B)

In [0]:
print(transposed.shape, '\n', transposed2.shape)

(3, 6) 
 (3, 6)


In [0]:
transposed2 = transposed2.reshape(6, 3)
print(transposed.shape, '\n', transposed2.shape)

(3, 6) 
 (6, 3)


In [0]:
print(np.dot(transposed, transposed2))

[[591 642 693]
 [642 699 756]
 [693 756 819]]


In [0]:
# Automatically considers that they are matrixes so it
# does the dot product too
print(transposed * transposed2)

[[591 642 693]
 [642 699 756]
 [693 756 819]]


In [0]:
print(transposed2 * transposed)

[[ 14  32  50  68  86 104]
 [ 32  77 122 167 212 257]
 [ 50 122 194 266 338 410]
 [ 68 167 266 365 464 563]
 [ 86 212 338 464 590 716]
 [104 257 410 563 716 869]]


In [0]:
A = np.matrix('2 4 4; 1 2 3')
B = np.matrix('1 3 4 5 6 7; 8 9 10 11 12 13; 14 15 16 17 18 19')
print(A.shape, B.shape)

(2, 3) (3, 6)


In [0]:
print(np.dot(A, B))

[[ 90 102 112 122 132 142]
 [ 59  66  72  78  84  90]]


In [0]:
print(np.dot(B, A)) # Column_B != Row_A

ValueError: ignored



---



### Scalar and Vector Division

* **To divide matrices, both their rows and columns must be the same.**

* shape(3,6) / shape(3,6) can be divided

In [0]:
# Could not be divided.
print(transposed.shape, '\n', transposed2.shape)

(3, 6) 
 (6, 3)


In [0]:
transposed = transposed.reshape(6, 3)
print(transposed.shape, '\n', transposed2.shape)

(6, 3) 
 (6, 3)


In [0]:
print(np.divide(transposed, transposed2 ))

[[1.         2.         2.33333333]
 [2.5        2.6        2.66666667]
 [0.28571429 0.625      0.88888889]
 [1.1        1.27272727 1.41666667]
 [0.23076923 0.42857143 0.6       ]
 [0.75       0.88235294 1.        ]]


In [0]:
print(transposed2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [0]:
transposed2 = np.delete(transposed2, 2, 1)
print(transposed2, transposed.shape, transposed2.shape)

[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]
 [13 14]
 [16 17]] (6, 3) (6, 2)


In [0]:
print(np.divide(transposed2, transposed ))

ValueError: ignored



---



### Exponentials and Roots

In [0]:
print(np.sqrt(transposed))

[[1.         2.         2.64575131]
 [3.16227766 3.60555128 4.        ]
 [1.41421356 2.23606798 2.82842712]
 [3.31662479 3.74165739 4.12310563]
 [1.73205081 2.44948974 3.        ]
 [3.46410162 3.87298335 4.24264069]]


In [0]:
print(np.power(transposed, 10))

[[            1       1048576     282475249]
 [  10000000000  137858491849 1099511627776]
 [         1024       9765625    1073741824]
 [  25937424601  289254654976 2015993900449]
 [        59049      60466176    3486784401]
 [  61917364224  576650390625 3570467226624]]


## Numpy Matrix Statistics Operations

* **We will almost never have to find the statistics for a whole matrix. **

* **It is mostly used for specified columns and rows**

### Mean

In [0]:
transposed.mean()

9.5

In [0]:
print(np.power(transposed, 2).mean())

117.16666666666667


### Variance

In [0]:
transposed2.var()

26.5

In [0]:
print(np.sqrt(transposed).var())

0.8841629857801211


### Standard Deviation

In [0]:
matrix.std()

5.188127472091127

In [0]:
np.sqrt(matrix.var()) # The std is the square-root of the variance

5.188127472091127

# Pandas Dataframe for 2d Data

* ** Dataframe: 2D structure that countains a list or dict in a series**

## Initializing and Converting to Panda DataFrames

In [0]:
import pandas as pd
import numpy as np

### Create DataFrame without index (list)

In [0]:
df = pd.DataFrame([[1,2,3], [4,5,6],[7,8,9]])
print(df)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9




---



### Create DataFrame with index (dictionary)

* **The keys are the columns, values are the rows**

In [0]:
df2 = pd.DataFrame({'col1': [2,4,5], 'col2':[10,20,30], 'col3': [3,9,12]})
print(df2)

   col1  col2  col3
0     2    10     3
1     4    20     9
2     5    30    12




---



### Convert Numpy Matrix to DataFrame

In [0]:
m = np.matrix([[1,2,3,],[2,4,6]])
print(m)

[[1 2 3]
 [2 4 6]]


In [0]:
df3 = pd.DataFrame(m)
print(df3)

   0  1  2
0  1  2  3
1  2  4  6




---



### Convert files/databases

In [0]:
from google.colab import files
uploaded = files.upload()
for fn in uploaded.keys():
  print('User uploaded files "{name}" with {length} bytes'.format(name=fn, length = len(uploaded[fn])))

Saving NewDB.db to NewDB.db
User uploaded files "NewDB.db" with 8192 bytes


In [0]:
import pandas as pd
import sqlite3

con = sqlite3.connect("Sales.db")

In [0]:
con2 = sqlite3.connect("NewDB.db")

In [0]:
con3 = sqlite3.connect("Supplier.db")

In [0]:
c = con2.cursor()
c3 = con3.cursor()

In [54]:
c.execute( 'CREATE TABLE Employee(Employee_ID INTEGER PRIMARY KEY, First_Name TEXT, Last_Name Text, Department TEXT, City TEXT)')

In [56]:
c3.execute("CREATE TABLE Product(Product_ID INTEGERS PRIMARY KEY, Product_Name TEXT, Price INTEGERS, Supplier_ID INTEGERS, Supplier_Name TEXT)")


In [58]:

products = [
    (30001, 'T-Shirt', 12.98, 40004, "Studio Warehouse"),
    (30002, 'Tooth Paste', 4.5, 40002, "BioMed Inc"),
    (30003, 'Speakers', 56.99, 40005, "CompTech, Inc"),
    (30004, 'Pants', 34.35, 40003, "FashionRUs"),
    (30005, 'Microphone', 46.21, 40001, "Music Vibrations, Inc"),
    (30006, 'Tie', 11.09, 40003, "FashionRUs"),
    (30007, 'Chap Stick', 3.67, 40002, "BioMed Inc"),
    (30008, 'Medicine', 23.96, 40002, "BioMed Inc"),
    (30009, 'Headhphones', 31.44, 40001, "Music Vibrations, Inc"),
    (30010, 'Lotion', 16.77, 40002, "BioMed Inc"),
    (30011, 'DVD Plyaer', 149.99, 40005, "CompTech, Inc"),
    (30012, 'Coat', 56.33, 40004, "Studio Warehouse"),
]

c3.executemany('INSERT INTO Product VALUES (?,?,?,?,?)', products)

* ** Querying all tables in DB**

In [0]:
print(pd.read_sql_query("select name from sqlite_master where type = 'table'", con))
print(pd.read_sql_query("select name from sqlite_master where type = 'table'", con2))
print(pd.read_sql_query("select name from sqlite_master where type = 'table'", con3))

        name
0     Orders
1  Customers
       name
0  Employee
       name
0  Supplier
1   Product


In [0]:
employees = [
    (10002, 'Nick', 'Markmen', 'Clothes', 'San Franciso'), 
    (10003, 'Maria', 'Gonzalez', 'Electronics', 'San Jose'),
    (10004, 'George', 'Wong', 'Clothes', 'San Franciso'),
    (10005, 'Stephanie', 'Williams', 'Clothes', 'Oakland'),
    (10006, 'Miguel', 'Alva', 'Clothes', 'Oakland'),
    (10007, 'Jessica', 'Collins', 'Cosmetics', 'San Franciso'),
    (10008, 'Ted', 'Anderson', 'Clothes', 'Oakland'),
    (10009, 'Victoria', 'Garcia', 'Clothes', 'San Jose'),
    (10010, 'Jasmine', 'Khan', 'Parmacy Health & Beauty', 'Oakland'),
    (10011, 'Adam', 'Smith', 'Parmacy Health & Beauty', 'San Jose'),
    (10012, 'Rachel', 'Kim', 'Electronics', 'San Jose'),
]

In [0]:
c.executemany("INSERT INTO Employee VALUES (?,?,?,?,?)", employees)



---



#### Tables

* **Asigning panda df of tables**

In [0]:
customer_df = pd.read_sql_query("SELECT * FROM Customers", con)
print(customer_df)

In [0]:
order_df = pd.read_sql_query("SELECT * FROM Orders", con)
print(order_df)

In [0]:
employee_df = pd.read_sql_query("SELECT * FROM Employee", con2)
print(employee_df)

    Employee_ID First_Name Last_Name               Department          City
0         10002       Nick   Markmen                  Clothes  San Franciso
1         10003      Maria  Gonzalez              Electronics      San Jose
2         10004     George      Wong                  Clothes  San Franciso
3         10005  Stephanie  Williams                  Clothes       Oakland
4         10006     Miguel      Alva                  Clothes       Oakland
5         10007    Jessica   Collins                Cosmetics  San Franciso
6         10008        Ted  Anderson                  Clothes       Oakland
7         10009   Victoria    Garcia                  Clothes      San Jose
8         10010    Jasmine      Khan  Parmacy Health & Beauty       Oakland
9         10011       Adam     Smith  Parmacy Health & Beauty      San Jose
10        10012     Rachel       Kim              Electronics      San Jose


In [0]:
product_df = pd.read_sql_query("Select * from Product", con3)
print(product_df)

    Product_ID Product_Name   Price  Supplier_ID          Supplier_Name
0        30001      T-Shirt   12.98        40004       Studio Warehouse
1        30002  Tooth Paste    4.50        40002             BioMed Inc
2        30003     Speakers   56.99        40005          CompTech, Inc
3        30004        Pants   34.35        40003             FashionRUs
4        30005   Microphone   46.21        40001  Music Vibrations, Inc
5        30006          Tie   11.09        40003             FashionRUs
6        30007   Chap Stick    3.67        40002             BioMed Inc
7        30008     Medicine   23.96        40002             BioMed Inc
8        30009  Headhphones   31.44        40001  Music Vibrations, Inc
9        30010       Lotion   16.77        40002             BioMed Inc
10       30011   DVD Plyaer  149.99        40005          CompTech, Inc
11       30012         Coat   56.33        40004       Studio Warehouse


In [0]:
supplier_df = pd.read_sql_query("SELECT * FROM Supplier", con3)
print(supplier_df)



---



## Accessing and Selection

In [0]:
employee_df['First_Name']

0          Nick
1         Maria
2        George
3     Stephanie
4        Miguel
5       Jessica
6           Ted
7      Victoria
8       Jasmine
9          Adam
10       Rachel
Name: First_Name, dtype: object

In [0]:
employee_df[:].head(4)

Employee_ID First_Name Last_Name   Department          City
0        10002       Nick   Markmen      Clothes  San Franciso
1        10003      Maria  Gonzalez  Electronics      San Jose
2        10004     George      Wong      Clothes  San Franciso
3        10005  Stephanie  Williams      Clothes       Oakland

In [0]:
order_df[:]

num1   num2   num3   num4      Date
0  50010  20013  30004  10008  17-04-11
1  50011  20014  30005  10009  19-09-16
2  50020  20015  30005  10009  20-10-20



---



**Accessing ROWS by  table[col] [ row ]**

* ** Not suggested. **

* Too complex

In [0]:
employee_df['Last_Name'][1:4]

1    Gonzalez
2        Wong
3    Williams
Name: Last_Name, dtype: object



---



### Selection by Label *

** Recommended way**: Follow ( row, col) order**

In [0]:
df2.loc[:, ['col1', 'col2']]

col1  col2
0     2    10
1     4    20
2     5    30

In [0]:
supplier_df.loc[:]

Supplier_ID                   Name          City
0        40001  Music Vibrations, Inc       Oakland
1        40002             BioMed Inc  San Franciso
2        40003             FashionRUs      San Jose
3        40004       Studio Warehouse  San Franciso
4        40005          CompTech, Inc      San Jose

In [0]:
# Does not follow conventioal [:]

supplier_df.loc[2:4, ['City']]


City
2      San Jose
3  San Franciso
4      San Jose

In [0]:
supplier_df.loc[2:6, ['City', 'Name']]

City              Name
2      San Jose        FashionRUs
3  San Franciso  Studio Warehouse
4      San Jose     CompTech, Inc



---



### Selection by Position

In [0]:
supplier_df.iloc[2]

Supplier_ID         40003
Name           FashionRUs
City             San Jose
Name: 2, dtype: object

In [0]:
supplier_df.iloc[:2, :]

Supplier_ID                   Name          City
0        40001  Music Vibrations, Inc       Oakland
1        40002             BioMed Inc  San Franciso

In [0]:
customer_df.iloc[:]

Customer_ID First_Name  Last_Name       City
0        50010     Jeremy  Del Valle  Aguadilla
1        50011     Joshua  Del Valle    Isabela
2        50012    Natalia  Hernandez    Isabela
3        50013       Jose      Rojas  Aguadilla
4        50014     Carlos     Robles  Aguadilla

* ** This one does behave like regular [ : ]**

In [0]:
customer_df.iloc[:, 1:3]

First_Name  Last_Name
0     Jeremy  Del Valle
1     Joshua  Del Valle
2    Natalia  Hernandez
3       Jose      Rojas
4     Carlos     Robles

In [0]:
employee_df.iloc[4:10, 0]

4    10006
5    10007
6    10008
7    10009
8    10010
9    10011
Name: Employee_ID, dtype: int64

In [0]:
employee_df.iloc[4:6, 1:3]

First_Name Last_Name
4     Miguel      Alva
5    Jessica   Collins



---



### Selection by Slicing

In [0]:
employee_df.loc[1:3, ['First_Name']]

First_Name
1      Maria
2     George
3  Stephanie

In [0]:
employee_df.loc[1:3, 'First_Name':'Last_Name']

First_Name Last_Name
1      Maria  Gonzalez
2     George      Wong
3  Stephanie  Williams

$$.iloc treats [ : ]$$  like normal

In [0]:

employee_df.iloc[1:3, 1:3]

First_Name Last_Name
1      Maria  Gonzalez
2     George      Wong



---



### Access by Condition AND OR NOT

In [0]:
product_df.loc[:]

Product_ID Product_Name   Price  Supplier_ID          Supplier_Name
0        30001      T-Shirt   12.98        40004       Studio Warehouse
1        30002  Tooth Paste    4.50        40002             BioMed Inc
2        30003     Speakers   56.99        40005          CompTech, Inc
3        30004        Pants   34.35        40003             FashionRUs
4        30005   Microphone   46.21        40001  Music Vibrations, Inc
5        30006          Tie   11.09        40003             FashionRUs
6        30007   Chap Stick    3.67        40002             BioMed Inc
7        30008     Medicine   23.96        40002             BioMed Inc
8        30009  Headhphones   31.44        40001  Music Vibrations, Inc
9        30010       Lotion   16.77        40002             BioMed Inc
10       30011   DVD Plyaer  149.99        40005          CompTech, Inc
11       30012         Coat   56.33        40004       Studio Warehouse

In [0]:
product_df[product_df['Price'] > 50]

Product_ID Product_Name   Price  Supplier_ID     Supplier_Name
2        30003     Speakers   56.99        40005     CompTech, Inc
10       30011   DVD Plyaer  149.99        40005     CompTech, Inc
11       30012         Coat   56.33        40004  Studio Warehouse

In [0]:
product_df[(product_df['Product_ID'] > 30004) & (product_df['Price'] > 20)]

Product_ID Product_Name   Price  Supplier_ID          Supplier_Name
4        30005   Microphone   46.21        40001  Music Vibrations, Inc
7        30008     Medicine   23.96        40002             BioMed Inc
8        30009  Headhphones   31.44        40001  Music Vibrations, Inc
10       30011   DVD Plyaer  149.99        40005          CompTech, Inc
11       30012         Coat   56.33        40004       Studio Warehouse

In [0]:
product_df[(product_df['Price'] < 15) & (product_df['Supplier_Name'] == 'BioMed Inc') ]

Product_ID Product_Name  Price  Supplier_ID Supplier_Name
1       30002  Tooth Paste   4.50        40002    BioMed Inc
6       30007   Chap Stick   3.67        40002    BioMed Inc

In [0]:
product_df[(product_df['Product_Name'] == 'Pants') | (product_df['Product_Name'] == 'Tie') ]

Product_ID Product_Name  Price  Supplier_ID Supplier_Name
3       30004        Pants  34.35        40003    FashionRUs
5       30006          Tie  11.09        40003    FashionRUs

In [0]:
product_df[~(product_df['Product_Name'] == 'Pants') & ~(product_df['Product_Name'] == 'Tie') ]

Product_ID Product_Name   Price  Supplier_ID          Supplier_Name
0        30001      T-Shirt   12.98        40004       Studio Warehouse
1        30002  Tooth Paste    4.50        40002             BioMed Inc
2        30003     Speakers   56.99        40005          CompTech, Inc
3        30004        Pants   34.35        40003             FashionRUs
4        30005   Microphone   46.21        40001  Music Vibrations, Inc
5        30006          Tie   11.09        40003             FashionRUs
6        30007   Chap Stick    3.67        40002             BioMed Inc
7        30008     Medicine   23.96        40002             BioMed Inc
8        30009  Headhphones   31.44        40001  Music Vibrations, Inc
9        30010       Lotion   16.77        40002             BioMed Inc
10       30011   DVD Plyaer  149.99        40005          CompTech, Inc
11       30012         Coat   56.33        40004       Studio Warehouse



---



### Iterations

* ** Not something that is normally done**

In [0]:
print(employee_df)

    Employee_ID First_Name Last_Name               Department          City
0         10002       Nick   Markmen                  Clothes  San Franciso
1         10003      Maria  Gonzalez              Electronics      San Jose
2         10004     George      Wong                  Clothes  San Franciso
3         10005  Stephanie  Williams                  Clothes       Oakland
4         10006     Miguel      Alva                  Clothes       Oakland
5         10007    Jessica   Collins                Cosmetics  San Franciso
6         10008        Ted  Anderson                  Clothes       Oakland
7         10009   Victoria    Garcia                  Clothes      San Jose
8         10010    Jasmine      Khan  Parmacy Health & Beauty       Oakland
9         10011       Adam     Smith  Parmacy Health & Beauty      San Jose
10        10012     Rachel       Kim              Electronics      San Jose


In [0]:
# data_frame.itertuples():
for row in employee_df.itertuples():
  print(row)

Pandas(Index=0, Employee_ID=10002, First_Name='Nick', Last_Name='Markmen', Department='Clothes', City='San Franciso')
Pandas(Index=1, Employee_ID=10003, First_Name='Maria', Last_Name='Gonzalez', Department='Electronics', City='San Jose')
Pandas(Index=2, Employee_ID=10004, First_Name='George', Last_Name='Wong', Department='Clothes', City='San Franciso')
Pandas(Index=3, Employee_ID=10005, First_Name='Stephanie', Last_Name='Williams', Department='Clothes', City='Oakland')
Pandas(Index=4, Employee_ID=10006, First_Name='Miguel', Last_Name='Alva', Department='Clothes', City='Oakland')
Pandas(Index=5, Employee_ID=10007, First_Name='Jessica', Last_Name='Collins', Department='Cosmetics', City='San Franciso')
Pandas(Index=6, Employee_ID=10008, First_Name='Ted', Last_Name='Anderson', Department='Clothes', City='Oakland')
Pandas(Index=7, Employee_ID=10009, First_Name='Victoria', Last_Name='Garcia', Department='Clothes', City='San Jose')
Pandas(Index=8, Employee_ID=10010, First_Name='Jasmine', Last

In [0]:
# data_frame.iterrows():
for index, row in employee_df.iterrows():
  print('\ni = ', index, row)


i =  0 Employee_ID           10002
First_Name             Nick
Last_Name           Markmen
Department          Clothes
City           San Franciso
Name: 0, dtype: object

i =  1 Employee_ID          10003
First_Name           Maria
Last_Name         Gonzalez
Department     Electronics
City              San Jose
Name: 1, dtype: object

i =  2 Employee_ID           10004
First_Name           George
Last_Name              Wong
Department          Clothes
City           San Franciso
Name: 2, dtype: object

i =  3 Employee_ID        10005
First_Name     Stephanie
Last_Name       Williams
Department       Clothes
City             Oakland
Name: 3, dtype: object

i =  4 Employee_ID      10006
First_Name      Miguel
Last_Name         Alva
Department     Clothes
City           Oakland
Name: 4, dtype: object

i =  5 Employee_ID           10007
First_Name          Jessica
Last_Name           Collins
Department        Cosmetics
City           San Franciso
Name: 5, dtype: object

i =  6 Employee_ID



---



### Limits/Sorting

In [0]:
employee_df

Employee_ID First_Name Last_Name               Department          City
0         10002       Nick   Markmen                  Clothes  San Franciso
1         10003      Maria  Gonzalez              Electronics      San Jose
2         10004     George      Wong                  Clothes  San Franciso
3         10005  Stephanie  Williams                  Clothes       Oakland
4         10006     Miguel      Alva                  Clothes       Oakland
5         10007    Jessica   Collins                Cosmetics  San Franciso
6         10008        Ted  Anderson                  Clothes       Oakland
7         10009   Victoria    Garcia                  Clothes      San Jose
8         10010    Jasmine      Khan  Parmacy Health & Beauty       Oakland
9         10011       Adam     Smith  Parmacy Health & Beauty      San Jose
10        10012     Rachel       Kim              Electronics      San Jose

* ** Alphabetical order **

In [0]:
employee_df.sort_values(by=['Last_Name'])

Employee_ID First_Name Last_Name               Department          City
4         10006     Miguel      Alva                  Clothes       Oakland
6         10008        Ted  Anderson                  Clothes       Oakland
5         10007    Jessica   Collins                Cosmetics  San Franciso
7         10009   Victoria    Garcia                  Clothes      San Jose
1         10003      Maria  Gonzalez              Electronics      San Jose
8         10010    Jasmine      Khan  Parmacy Health & Beauty       Oakland
10        10012     Rachel       Kim              Electronics      San Jose
0         10002       Nick   Markmen                  Clothes  San Franciso
9         10011       Adam     Smith  Parmacy Health & Beauty      San Jose
3         10005  Stephanie  Williams                  Clothes       Oakland
2         10004     George      Wong                  Clothes  San Franciso

In [0]:
employee_df.sort_values(by=['Last_Name']).tail(2)

Employee_ID First_Name Last_Name Department     City
4        10006     Miguel      Alva    Clothes  Oakland
6        10008        Ted  Anderson    Clothes  Oakland



---



## Modifying Panda DataFrames

In [0]:
customer_df.head(3)

Customer_ID First_Name  Last_Name       City
0        50010     Jeremy  Del Valle  Aguadilla
1        50011     Joshua  Del Valle    Isabela
2        50012    Natalia  Hernandez    Isabela

In [0]:
order_df

num1   num2   num3   num4      Date
0  50010  20013  30004  10008  17-04-11
1  50011  20014  30005  10009  19-09-16
2  50020  20015  30005  10009  20-10-20

### Merging *

* ** 'inner' find matches**

In [0]:
print(customer_df.head(3),'\n', order_df.head(3))

   Customer_ID First_Name  Last_Name       City
0        50010     Jeremy  Del Valle  Aguadilla
1        50011     Joshua  Del Valle    Isabela
2        50012    Natalia  Hernandez    Isabela 
    Customer_ID   num2   num3   num4
0        50010  20013  30004  10008
1        50011  20014  30005  10009
2        50020  20015  30005  10009


* Matches Customer_ID

In [0]:
pd.merge(customer_df, order_df, how='inner')

Customer_ID First_Name  Last_Name       City   num2   num3   num4
0        50010     Jeremy  Del Valle  Aguadilla  20013  30004  10008
1        50011     Joshua  Del Valle    Isabela  20014  30005  10009

In [0]:
pd.merge(customer_df, order_df, how='left')

Customer_ID First_Name  Last_Name       City     num2     num3     num4
0        50010     Jeremy  Del Valle  Aguadilla  20013.0  30004.0  10008.0
1        50011     Joshua  Del Valle    Isabela  20014.0  30005.0  10009.0
2        50012    Natalia  Hernandez    Isabela      NaN      NaN      NaN
3        50013       Jose      Rojas  Aguadilla      NaN      NaN      NaN
4        50014     Carlos     Robles  Aguadilla      NaN      NaN      NaN

In [0]:
pd.merge(customer_df, order_df, how='right')

Customer_ID First_Name  Last_Name       City   num2   num3   num4
0        50010     Jeremy  Del Valle  Aguadilla  20013  30004  10008
1        50011     Joshua  Del Valle    Isabela  20014  30005  10009
2        50020        NaN        NaN        NaN  20015  30005  10009



---



### Append/Concatenate

In [0]:
supplier_df = pd.DataFrame({'Supplier_ID': [40006, 40007], 'Name': ['GameHub Inc', 'TechCenter Media'], 'City': ['Atlanta', 'New York']})

* **Append is similair to Union in SQL**

In [0]:
supplier_df.append(order_df)

City  Customer_ID              Name  Supplier_ID     num2     num3  \
0   Atlanta          NaN       GameHub Inc      40006.0      NaN      NaN   
1  New York          NaN  TechCenter Media      40007.0      NaN      NaN   
0       NaN      50010.0               NaN          NaN  20013.0  30004.0   
1       NaN      50011.0               NaN          NaN  20014.0  30005.0   
2       NaN      50020.0               NaN          NaN  20015.0  30005.0   

      num4  
0      NaN  
1      NaN  
0  10008.0  
1  10009.0  
2  10009.0



---



* ** Concatenate**
* * second Dataframe concatenated below the first by default.

In [0]:
pd.concat([supplier_df, order_df])

City  Customer_ID              Name  Supplier_ID     num2     num3  \
0   Atlanta          NaN       GameHub Inc      40006.0      NaN      NaN   
1  New York          NaN  TechCenter Media      40007.0      NaN      NaN   
0       NaN      50010.0               NaN          NaN  20013.0  30004.0   
1       NaN      50011.0               NaN          NaN  20014.0  30005.0   
2       NaN      50020.0               NaN          NaN  20015.0  30005.0   

      num4  
0      NaN  
1      NaN  
0  10008.0  
1  10009.0  
2  10009.0

* ** Using axis**

In [0]:
supplier_df

City              Name  Supplier_ID
0   Atlanta       GameHub Inc        40006
1  New York  TechCenter Media        40007

In [0]:
pd.concat([order_df, supplier_df], axis=1)

Customer_ID   num2   num3   num4      City              Name  Supplier_ID
0        50010  20013  30004  10008   Atlanta       GameHub Inc      40006.0
1        50011  20014  30005  10009  New York  TechCenter Media      40007.0
2        50020  20015  30005  10009       NaN               NaN          NaN



---



### Deleteing/Droping


In [0]:
supplier_df.drop([1])

City         Name  Supplier_ID
0  Atlanta  GameHub Inc        40006

In [0]:
supplier_df.drop(['Name'], axis=1)

City  Supplier_ID
0   Atlanta        40006
1  New York        40007



---



### Updating

In [0]:
supplier_df.loc[1]= ['Puerto Rico', 'TechCenter', 40005]  
print(supplier_df)

          City         Name  Supplier_ID
0      Atlanta  GameHub Inc        40006
1  Puerto Rico   TechCenter        40005


In [0]:
supplier_df.loc[1, 'Supplier_ID'] +=6000

In [0]:
print(supplier_df)

          City         Name  Supplier_ID
0      Atlanta  GameHub Inc        40006
1  Puerto Rico   TechCenter        46005


In [0]:
supplier_df['Supplier_ID'].update(pd.Series([9999, 9999]))

In [0]:
supplier_df

City         Name  Supplier_ID
0      Atlanta  GameHub Inc         9999
1  Puerto Rico   TechCenter         9999



---



### Stacking/Grouping

In [0]:
supplier_df.stack()

0  City               Atlanta
   Name           GameHub Inc
   Supplier_ID           9999
1  City           Puerto Rico
   Name            TechCenter
   Supplier_ID           9999
dtype: object

In [0]:
order_df.stack()

0  Customer_ID    50010
   num2           20013
   num3           30004
   num4           10008
1  Customer_ID    50011
   num2           20014
   num3           30005
   num4           10009
2  Customer_ID    50020
   num2           20015
   num3           30005
   num4           10009
dtype: int64

### **Group by**

* Similair to SQL group by

In [0]:
employee_df.head(4)

Employee_ID First_Name Last_Name   Department          City
0        10002       Nick   Markmen      Clothes  San Franciso
1        10003      Maria  Gonzalez  Electronics      San Jose
2        10004     George      Wong      Clothes  San Franciso
3        10005  Stephanie  Williams      Clothes       Oakland

In [0]:
employee_df.groupby('City').count()

Employee_ID  First_Name  Last_Name  Department
City                                                        
Oakland                 4           4          4           4
San Franciso            3           3          3           3
San Jose                4           4          4           4

In [0]:
h = employee_df.groupby('City')
print(h)

In [0]:
product_df

Product_ID Product_Name   Price  Supplier_ID          Supplier_Name
0        30001      T-Shirt   12.98        40004       Studio Warehouse
1        30002  Tooth Paste    4.50        40002             BioMed Inc
2        30003     Speakers   56.99        40005          CompTech, Inc
3        30004        Pants   34.35        40003             FashionRUs
4        30005   Microphone   46.21        40001  Music Vibrations, Inc
5        30006          Tie   11.09        40003             FashionRUs
6        30007   Chap Stick    3.67        40002             BioMed Inc
7        30008     Medicine   23.96        40002             BioMed Inc
8        30009  Headhphones   31.44        40001  Music Vibrations, Inc
9        30010       Lotion   16.77        40002             BioMed Inc
10       30011   DVD Plyaer  149.99        40005          CompTech, Inc
11       30012         Coat   56.33        40004       Studio Warehouse

In [0]:
employee_df.groupby('Department').count()

Employee_ID  First_Name  Last_Name  City
Department                                                       
Clothes                            6           6          6     6
Cosmetics                          1           1          1     1
Electronics                        2           2          2     2
Parmacy Health & Beauty            2           2          2     2

In [0]:
product_df[['Supplier_Name', 'Price']].groupby('Supplier_Name').sum()

Price
Supplier_Name                
BioMed Inc              48.90
CompTech, Inc          206.98
FashionRUs              45.44
Music Vibrations, Inc   77.65
Studio Warehouse        69.31

In [0]:
product_df[['Supplier_Name', 'Price', 'Product_ID']].groupby('Supplier_Name').sum() # It added the ID's too

Price  Product_ID
Supplier_Name                            
BioMed Inc              48.90      120027
CompTech, Inc          206.98       60014
FashionRUs              45.44       60010
Music Vibrations, Inc   77.65       60014
Studio Warehouse        69.31       60013

In [0]:
product_df[['Supplier_Name', 'Price', 'Product_ID']].groupby(['Supplier_Name', 'Product_ID']).sum() 

Price
Supplier_Name         Product_ID        
BioMed Inc            30002         4.50
                      30007         3.67
                      30008        23.96
                      30010        16.77
CompTech, Inc         30003        56.99
                      30011       149.99
FashionRUs            30004        34.35
                      30006        11.09
Music Vibrations, Inc 30005        46.21
                      30009        31.44
Studio Warehouse      30001        12.98
                      30012        56.33

##Panda DataFrame Math Operations

In [0]:
import pandas as pd
import numpy as np

In [31]:
m = np.matrix('1 2 3; 4 5 6; 7 8 9')
m2 = np.matrix('10 30 40; 20 40 50; 14 15 20')
m3 = np.matrix('10 100; 20 200')
df = pd.DataFrame(m)
df2 = pd.DataFrame(m2)
df3 = pd.DataFrame(np.matrix('10 100; 20 200'))
print(df, '\n\n', df2, '\n\n', df3)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9 

     0   1   2
0  10  30  40
1  20  40  50
2  14  15  20 

     0    1
0  10  100
1  20  200


### Scalar and Vector Addition

In [13]:
df + df2

0   1   2
0  11  32  43
1  24  45  56
2  21  23  29

### Scalar and Vector Subtraction

In [18]:
df2-df

0   1   2
0   9  28  37
1  16  35  44
2   7   7  11

### Scalar and Vector Multiplication

In [21]:
df*10

0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [22]:
df * df2 # Multiplying DataFrames by elements. 

0    1    2
0  10   60  120
1  80  200  300
2  98  120  180

In [25]:
m * m2 # Multiplying Matrices gives the dot products

matrix([[ 92, 155, 200],
        [224, 410, 530],
        [356, 665, 860]])

In [26]:
pd.DataFrame(m * m2)

0    1    2
0   92  155  200
1  224  410  530
2  356  665  860



---





### Scalar and Vector division

In [27]:
df2 / 10

0    1    2
0  1.0  3.0  4.0
1  2.0  4.0  5.0
2  1.4  1.5  2.0

In [28]:
df/df2

0         1      2
0  0.1  0.066667  0.075
1  0.2  0.125000  0.120
2  0.5  0.533333  0.450

* **Data Frames of different shapes can be divided**

In [30]:
df/df3

0      1   2
0  0.1  0.020 NaN
1  0.2  0.025 NaN
2  NaN    NaN NaN

* **Matrices cannot**

In [32]:
m/m3

ValueError: ignored



---



### Exponentials/Roots

In [33]:
df2 **3

0      1       2
0  1000  27000   64000
1  8000  64000  125000
2  2744   3375    8000

* **Numpy can also work with dataframes**

In [36]:
np.power(df2, 3)

0      1       2
0  1000  27000   64000
1  8000  64000  125000
2  2744   3375    8000



---



## Panda DataFrame Statistics Operations

### Min/Max/Range

* **Prints out the mininmum of Each Column **

In [39]:
df2.min()

0    10
1    15
2    20
dtype: int64

In [40]:
df2

0   1   2
0  10  30  40
1  20  40  50
2  14  15  20

In [41]:
df2.max() # Goes by column

0    20
1    40
2    50
dtype: int64

In [42]:
# Ranges
df2  .max() - df2.min()

0    10
1    25
2    30
dtype: int64

### Sum/Total

* ** Sums by column**

In [44]:
df2.sum()

0     44
1     85
2    110
dtype: int64

### Count/Frequency

In [45]:
df.count() # how many entries per column

0    3
1    3
2    3
dtype: int64

In [62]:
product_df = pd.read_sql_query('SELECT * FROM Product', con3)
product_df.count()

Product_ID       12
Product_Name     12
Price            12
Supplier_ID      12
Supplier_Name    12
dtype: int64

In [63]:
product_df

Product_ID Product_Name   Price  Supplier_ID          Supplier_Name
0        30001      T-Shirt   12.98        40004       Studio Warehouse
1        30002  Tooth Paste    4.50        40002             BioMed Inc
2        30003     Speakers   56.99        40005          CompTech, Inc
3        30004        Pants   34.35        40003             FashionRUs
4        30005   Microphone   46.21        40001  Music Vibrations, Inc
5        30006          Tie   11.09        40003             FashionRUs
6        30007   Chap Stick    3.67        40002             BioMed Inc
7        30008     Medicine   23.96        40002             BioMed Inc
8        30009  Headhphones   31.44        40001  Music Vibrations, Inc
9        30010       Lotion   16.77        40002             BioMed Inc
10       30011   DVD Plyaer  149.99        40005          CompTech, Inc
11       30012         Coat   56.33        40004       Studio Warehouse

### MeanMedian


In [65]:
df2

0   1   2
0  10  30  40
1  20  40  50
2  14  15  20

In [64]:
df2.mean() # By columns

0    14.666667
1    28.333333
2    36.666667
dtype: float64

In [66]:
df2.median()

0    14.0
1    30.0
2    40.0
dtype: float64

### Variance/Standard Deviation

In [69]:
variance = df2.var()
print(variance)

0     25.333333
1    158.333333
2    233.333333
dtype: float64


In [71]:
print(df2.std())
print(np.sqrt(variance))

0     5.033223
1    12.583057
2    15.275252
dtype: float64
0     5.033223
1    12.583057
2    15.275252
dtype: float64


###  Covariance

* ** Covariance calculates how 2 different variable vary together**

In [72]:
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

* **Returns in pair-wise covariance of columns

In [74]:
df.cov()

0    1    2
0  9.0  9.0  9.0
1  9.0  9.0  9.0
2  9.0  9.0  9.0

In [0]:
df2 = pd.DataFrame([[1,2], [2,4],[3,6],[4,8]])

In [76]:
df2.cov()

0         1
0  1.666667  3.333333
1  3.333333  6.666667

### Quantile

In [77]:
df2.quantile([0, .25, .28, .75])

0     1
0.00  1.00  2.00
0.25  1.75  3.50
0.28  1.84  3.68
0.75  3.25  6.50

### Cumulative Sum

In [78]:
df2.cumsum()

0   1
0   1   2
1   3   6
2   6  12
3  10  20

In [79]:
df2

0  1
0  1  2
1  2  4
2  3  6
3  4  8

###  Aggregate Functions/Describe *

* **Several Statisctic calculations together**

In [91]:
df2.agg(['var', 'std', 'sum', 'mean', 'median'])

0          1
var      1.666667   6.666667
std      1.290994   2.581989
sum     10.000000  20.000000
mean     2.500000   5.000000
median   2.500000   5.000000

In [86]:
df2.sum()

0    10
1    20
dtype: int64

* **Quick and easy way to get all the statistics**

In [92]:
df2.describe()

0         1
count  4.000000  4.000000
mean   2.500000  5.000000
std    1.290994  2.581989
min    1.000000  2.000000
25%    1.750000  3.500000
50%    2.500000  5.000000
75%    3.250000  6.500000
max    4.000000  8.000000

### Apply/Lambda

* $df.apply()$ Allows us to apply any function to the data frame

In [94]:
df2.apply(['max'])

0  1
max  4  8

Even our own functions

In [0]:
def add_ten(x):
  return x + 10

In [97]:
df2.apply(add_ten)

0   1
0  11  12
1  12  14
2  13  16
3  14  18

In [99]:
product_df['Price'].apply(add_ten)

0      22.98
1      14.50
2      66.99
3      44.35
4      56.21
5      21.09
6      13.67
7      33.96
8      41.44
9      26.77
10    159.99
11     66.33
Name: Price, dtype: float64

In [98]:
product_df['Price']

0      12.98
1       4.50
2      56.99
3      34.35
4      46.21
5      11.09
6       3.67
7      23.96
8      31.44
9      16.77
10    149.99
11     56.33
Name: Price, dtype: float64



---



In [100]:
prod_min = product_df['Price'].min()
prod_max = product_df['Price'].max()
print(prod_min)
print(prod_max)

3.67
149.99


In [101]:
product_df['Price'].apply(lambda x: (prod_max - x)/(prod_max - prod_min))

0     0.936372
1     0.994328
2     0.635593
3     0.790323
4     0.709267
5     0.949289
6     1.000000
7     0.861331
8     0.810210
9     0.910470
10    0.000000
11    0.640104
Name: Price, dtype: float64

In [102]:
product_df['Price']

0      12.98
1       4.50
2      56.99
3      34.35
4      46.21
5      11.09
6       3.67
7      23.96
8      31.44
9      16.77
10    149.99
11     56.33
Name: Price, dtype: float64



---



In [103]:
product_supplier_df = pd.merge(product_df, supplier_df, how='inner')

NameError: ignored